---
#
# Ansible managed
#
repository:
  description: Install the checkmk agent and a selection of plugins
  homepage: https://buluma.github.io/
  topics: , ansible, molecule, tox, playbook, hacktoberfest
