---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    checkmk_purge_xinetd: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: buluma.checkmk_agent
      checkmk_server: 127.0.0.1
      checkmk_site_name: mysite
