---
- name: Verify
  hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: Run checkmk
      ansible.builtin.shell:
        cmd: omd version > omd.version
      args:
        creates: omd.version
